---
# tasks file for apt-setup
- name: apt-setup | Disable timers for unattended upgrade, so that none will be triggered by the `date -s` call.
  systemd:
    enabled: no
    name:  "{{item}}"
  with_items:
    - 'apt-daily.timer'
    - 'apt-daily-upgrade.timer'
  become: True


- name: apt-setup | Reload systemctl daemon to apply the new changes
  systemd:
    daemon_reload: True
  become: True

- name: apt-setup | Wait for any possibly running unattended upgrade to finish
  command:
    argv:
      - systemd-run
      - --property
      - After=apt-daily.service apt-daily-upgrade.service
      - --wait
      - /bin/true
  become: True

- name: apt-setup | Purge unattended upgrades
  apt:
    name: unattended-upgrades
    state: absent
    update_cache: True
  become: True

- name: apt-setup | Enable apt proxy
  template:
    src: "{{ role_path }}/templates/01proxy.j2"
    dest: /etc/apt/apt.conf.d/01proxy
    owner: root
    group: root
    mode: 0644
  become: True
  when: apt_proxy is defined
