---
# tasks file for avahi

- name: avahi | install daemon
  apt:
    name:
      - avahi-daemon
      - avahi-utils
    state: present
    update_cache: True
  become: true

- name: avahi | enable daemon
  systemd:
    name: avahi-daemon
    state: started
    enabled: True
  become: True
