---
# tasks file for swarm-first-manager

- name: swarm-first-manager | Initialize the swarm cluster
  docker_swarm:
    state: present
    advertise_addr: "{{ first_manager_ip }}"
  register: swarm_info

- name: swarm-first-manager | Copy worker join token to local file
  copy:
    content: "{{ swarm_info.swarm_facts.JoinTokens.Worker }}"
    dest: "./join-token-worker"
  delegate_to: localhost
  become: false

- name: swarm-first-manager | Copy manager join token to local file
  copy:
    content: "{{ swarm_info.swarm_facts.JoinTokens.Manager }}"
    dest: "./join-token-manager"
  delegate_to: localhost
  become: false
