---
# tasks file for deploy-portainer
- name: deploy-portainer | create reverse-proxy network
  docker_network:
    name: "reverse-proxy"
    state: present
    attachable: True
    scope: swarm
    driver: overlay

- name: deploy-portainer | generate password hash
  set_fact:
    portainer_admin_password_hash: "{{ portainer_admin_password | password_hash('md5') }}"
  no_log: true

- name: deploy-portainer | Set portainer_secrets
  set_fact:
    portainer_secrets:
      - { name: PORTAINER_ADMIN_PASSWORD , data: "{{ portainer_admin_password }}" }
  no_log: true

- name: deploy-portainer | Set digests
  set_fact:
    digests: "{{ digests | default({}) | combine( {('portainer_' + secret.name  | string) :  ( secret.data | checksum  | truncate(10, true,''))} ) }}"
  no_log: true
  loop: "{{ portainer_secrets  }}"
  loop_control:
    loop_var: secret

- name: deploy-portainer | Create secrets
  docker_secret:
    name: "portainer_{{ secret.name }}_{{ digests['portainer_' + secret.name] }}"
    state: present
    data: "{{ secret.data }}"
  no_log: true
  loop:  "{{ portainer_secrets }}"
  loop_control:
    loop_var: secret

- name: deploy-portainer | create temp file
  tempfile:
    state: file
    suffix: ".yml"
  register: compose_file

- name: deploy-portainer | create temporary compose file
  template:
    src:  "{{ [ role_path, 'templates' , 'docker-compose.yml.j2'] | join('/') }}"
    dest: compose_file.path

- name: deploy-portainer | Deploy portainer stack
  docker_stack:
    name: portainer
    compose: compose_file.path
    prune: True
    with_registry_auth: True

- name: deploy-portainer | remove temporary compose file
  file:
    path: compose_file.path
    state: absent
