- name: Setup first manager
  hosts: first_manager
  gather_facts: True
  roles:
    - { role: auth }
    - { role: apt-setup }
    - { role: fluentbit }
    - { role: cadvisor }
    - { role: node-exporter }
    - { role: docker-install }
    - { role: swarm-first-manager }
    - { role: deploy-traefik }
    - { role: deploy-portainer }
    - { role: deploy-elasticsearch }
    - { role: deploy-jenkins }
    - { role: deploy-swarmprom }

