- name: Setup additional managers
  hosts:
    - additional_managers
    - workers
  gather_facts: True
  roles:
    - { role: auth }
    - { role: apt-setup }
    - { role: fluentbit }
    - { role: docker-install }
    - { role: swarm-join-node }
