- name: Setup additional nodes
  hosts:
    - additional_managers
    - workers
  gather_facts: True
  roles:
    - { role: auth }
    - { role: apt-setup }
    - { role: cadvisor }
    - { role: node-exporter }
    - { role: fluentbit }
    - { role: docker-install }
    - { role: swarm-join-node }
