---
# tasks file for cadvisor

- name: cadvisor | create directories
  become: yes
  file:
    path: "{{ item }}"
    recurse: yes
    state: directory
  with_items:
  - /opt/cadvisor

- name: cadvisor | download
  become: yes
  get_url:
    url: "{{ cadvisor_url }}/{{ cadvisor_version }}/cadvisor"
    checksum: "sha256:{{ cadvisor_checksum }}"
    dest: "/opt/cadvisor/cadvisor-{{ cadvisor_version }}"
    force: no
    mode: u=rwx,g=rx,o=rx

- name: cadvisor | symlink
  become: yes
  file:
    src: "/opt/cadvisor/cadvisor-{{ cadvisor_version }}"
    path: /opt/cadvisor/cadvisor
    force: yes
    state: link

- name: cadvisor | server systemd service
  become: yes
  template:
    dest: /etc/systemd/system/cadvisor.service
    src: systemd-system-cadvisor-service.j2
  notify: restart cadvisor
